spring:
  application:
    name: animeFlix
  datasource:
    url: jdbc:mysql://localhost:3306/animeFlix_dev?createDatabaseIfNotExist=true
    username: root
    password: master
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true

server:
  port: 8080
